### ISSUE TITLE
Make changes to every function possible

### ISSUE THREAD

**Issue by windy31** [saoudrizwan/claude-dev#112]
I propose other way of writing code with claude dev, that might reduce tokens drastically.
Here's how it is right now:
Claude HAS to write the whole code of an app, so it would be swapped in VS code.

I propose:
Add an additional prompt to claude.ai so it would write THE FUNCTIONS THAT IT CHANGES FULLY, and then claude dev takes those changed functions and swaps them, not the whole code.
This way it would take less tokens from the messages and would achieve more precise changes from claude.ai.

What do you think of this idea, or i didn't think about something?

**Comment by CiberNin** [comment]
Not doing this is an explicit design decision.
Restricting Claude to write only what it changes actively causes Claude's responses to be dumber (there's a whole paper on this effect).

It might make sense as a setting.

**Comment by jmchat** [comment]
I think this is a good approach cause what happens now if there is a big file with a lot of functions is that it fixes the one you want and then ends with "The rest will be the same ...." and then it proposes to delete all other functions :) because of the way it works now (swapping the whole code).

**Comment by saoudrizwan** [comment]
v1.5.16 now lets you edit claude's responses before accepting, so this should help with the "rest will be the same" (you can hit a 'revert block' button to undo this)
