### ISSUE TITLE
Claude Dev and Aider prompting question

### ISSUE THREAD

**Issue by drhouse** [saoudrizwan/claude-dev#131]
hey, thanks for Claude Dev. I'd been using Aider up until a few days ago when I first tried Claude Dev. I've been curious about whether my perceived increased success, in getting prompts to result in what I want through Dev, is real or imaginary. 

Afaik, the differences between the two are that Aider uses Git, Dev uses history and that both tools have their own set of internal prompt instructions. In theory, if the prompt instructions were the same from Dev to Aider, should Aider deliver the same results? Also, are there any plans to have Git with Dev be an option?

**Comment by saoudrizwan** [comment]
Thanks for the feedback friend! There's a lot of differences, but I built claude dev with the intention of getting the most out of claude 3.5 sonnet's nuances (rather than being model agnostic like aider) which is maybe why you're getting different results. 
If you'd like a similar git functionality you can just prompt claude dev to git commit every now and then, summarizing recent changes in the commit message (in fact you could put this in 'custom instructions' in settings to do this across tasks)

**Comment by mkearl** [comment]
Can you give us an example of system instructions for a successful git functionality?

**Comment by saoudrizwan** [comment]
This has worked for me quite well:
```
At the start of any task, automatically check if the current directory is a git repository by running `git status`. If it’s not, initialize a git repository with `git init`. After completing a task or making significant changes, automatically run `git commit -am` with a message summarizing the recent updates.
```

**Comment by stevebrainng** [comment]
> Thanks for the feedback friend! There's a lot of differences, but I built claude dev with the intention of getting the most out of claude 3.5 sonnet's nuances (rather than being model agnostic like aider) which is maybe why you're getting different results. If you'd like a similar git functionality you can just prompt claude dev to git commit every now and then, summarizing recent changes in the commit message (in fact you could put this in 'custom instructions' in settings to do this across tasks)

Thanks for the response, out of curiosity I wanted to contribute to the original question:

just like you said, Yes! there's a lot of difference, after checking Aider's source code, the system prompts processes are different. 
@drhouse said "Afaik, the differences between the two are that Aider uses Git, Dev uses history and that both tools have their own set of internal prompt instructions."

I think what he meant was that Aider AI uses git commit history for Context aware memory management, meaning that Aider can avoid making some mistakes that users are facing with ClaudeDev currently because it's more than just writing a system prompt to commit changes.

- Aider AI knows the recent changes from the git commit history.
- Aider can avoid overwriting files that just need an update, as mentioned in: #141 


I hope you get my point, and I would love to see that ClaudeDev is something that's awesome!

**Comment by saoudrizwan** [comment]
> Aider AI knows the recent changes from the git commit history.

Definitely want to add this to claude dev as well, a tool to get git log and then he could ask to look at certain commits and their changes. 

> Aider can avoid overwriting files that just need an update

I updated the tool prompt to see if that helps with that issue. I'm looking into ways to apply edits without outputting the whole file, but anthropic is coming out with a fast edit mode feature that uses speculative decoding that essentially speeds this up significantly. I'd like to wait to test that out before implementing some stopgap that could affect the quality of claude's output (asking to provide a structured output such as diff format like aider does has been shown to reduce reasoning abilities, ie asking it to do a hard math problem step by step usually fails if forced to do in json format)

**Comment by stevebrainng** [comment]
Thanks @saoudrizwan I appreciate your good work. 

I'm open to contribution in anyway. Ws thinking about the recent prompt caching functionality
