### ISSUE TITLE
Code is truncated

### ISSUE THREAD

**Issue by vblues** [saoudrizwan/claude-dev#14]
When the code file is long, it will make changes to the file and in places put comments like:
// Rest of the code remains the same
This essentially renders the code file useless.

**Comment by ErikMeinders** [comment]
+1

**Comment by saoudrizwan** [comment]
Apply edits is something I've realized is a pretty hard problem to solve. Currently Claude Dev asks Sonnet 3.5 for the whole file in its response, even if it only has to change one line of code. Not efficient I know, and I planned on optimizing this after the hackathon.

LLMs like Claude have a maximum # of output tokens they can respond with each API request, and so you'll likely see it get "lazy" when writing large amounts of code i.e. with "rest of the code remains the same". 

Cursor uses a fine tuned model trained on applying edits from a partial response to a whole file change, along with “speculative decoding” to speed up its responses (instead of inferring the next single token, it infers multiple tokens in parallel). This way it can take a lazy suggestion from a foundational (expensive) model like Sonnet 3.5 and use their lighter ft model to apply those suggestions to a large file much more affordably. (They also use a pretty interesting concept of 'Shadow Workspace' where they essentially use a hidden second instance of vscode to catch and fix any linting errors before applying the edits.)

Aider uses a diff strategy where it asks the LLM to respond with a unified diff format (like how you see with patches), which works much better than other diff strategies considering these models were likely trained on unified diffs at some point. However  asking for a whole file results in higher quality responses because 1) their training data likely includes way more whole files than unified diffs, and 2) it is forced to think with more tokens.

I want to build Claude Dev with the assumption that scaling laws will persist and LLMs will get better and cheaper, so I'd prefer not to incorporate hacks that would reduce its quality. Fortunately, [Anthropic recently doubled the max output token limit for Claude 3.5 Sonnet from 4096 to 8192 in their API](https://x.com/alexalbert__/status/1812921642143900036), and I will be updating Claude Dev with this change once the hackathon is over. This means way less lazy coding and we can maintain the quality of Claude's edits without compromise.

**Comment by bzimbelman** [comment]
I agree with your assessment to not go with the unified diff approach aider uses. I get way more diff errors messing up my code with aider than I get code errors occurring with this. One thing I do like with aider is that I can /undo changes and rollback as many changes as I want to. Its use of git for this is helpful as well. I think that kind of ability either utilizing git or some other mechanism would be a good feature for the roadmap.

**Comment by saoudrizwan** [comment]
v1.0.4 now uses 8192 output tokens, so there should be way less lazy coding. Please feel free to re-open if you continue to see this issue.

**Comment by CiberNin** [comment]
Could we automate this with some blacklisted phrases that automatically reply to claude"provide full updated code" or the like?
Also, I've read that adding to the system prompt is sometimes less effective than appending to user prompt.

**Comment by bigben3333** [comment]
Wouldn't it be simpler to ask Claude to always generate diff files? It would probably cost much less in terms of output tokens.

**Comment by vtempest** [comment]
- **Thanks so much, [saoudrizwan](https://github.com/saoudrizwan),  for this great api  to streamline coding and make bug fixing and brainstorming CODING IS A JOY WITH CLAUDE.DEV**
-

![Screenshot_20240828_133823](https://github.com/user-attachments/assets/984957ba-442e-44dd-bfea-9be9720000c1)

I am having this issue as well. The main reason to use in vscode sidebar is to integrate directly into code with a diff and not have to copy and paste. 

1. But if the file is truncated with  "rest of the code remains unchanged" then look for that message and dont go into diff mode, only show those lines as diffed. 
2. go into diff mode but automatically add the truncated parts of files. should be easy to match for the end and starts.
3. always put into the original prompt: **Always print all functions in the file and do not ever print a message that rest of the code remains unchanged to replace functions.**
4. let us customize the sysprompt

**Comment by monotykamary** [comment]
> Wouldn't it be simpler to ask Claude to always generate diff files? It would probably cost much less in terms of output tokens.

You can write a custom instruction to achieve this with unified diffing (YMMV, especially for Ruby like languages):

```
When editing files, please use the unified diff format to specify your changes. Follow these guidelines:

1. Start each diff with the file name, using '--- a/filename' for the original file and '+++ b/filename' for the modified file.
2. Use the standard unified diff syntax, including line numbers at the start of each hunk. Begin each hunk with @@ -start,count +start,count @@, where:
   - 'start' is the starting line number in the original file
   - 'count' is the number of lines in the hunk (including context lines)
   Use '1' for the count if you're adding new lines at the beginning or end of the file.

3. Provide coherent diffs that show the entire function or logical block of code being modified, including sufficient context.
4. Use '-' to indicate lines being removed, '+' to indicate lines being added, and ' ' (space) for unchanged context lines.
5. Include at least 3 lines of unchanged context before and after the changes to clearly locate the modification in the file.
6. For multiple changes in a file, use separate hunks divided by the @@ ... @@ marker.
7. Ensure that your diffs are complete and don't elide code with comments.
8. When editing a function or block, replace the entire block if possible.
9. To move code within a file, use 2 hunks: 1 to delete it from its current location, 1 to insert it in the new location.
10. Pay close attention to indentation and whitespace. They matter in the diffs!

Here's an example of a correctly formatted hunk:

\```diff
@@ -1,7 +1,9 @@
 defmodule Memo.WatchRun do
+  @moduledoc """
+  A GenServer that watches for file changes in a specified vault path and triggers
+  export scripts when changes are detected.
+  """
+
   use GenServer
   require Logger
 
-  # delay in milliseconds
-  @unlock_delay 2000
+  @unlock_delay Application.get_env(:memo, :unlock_delay, 2000)
\```

After providing the diff, explicitly state the commands to write the diff to a file in the .claude.dev folder and apply the changes:

Run the `write_to_file` tool for the diff file:

\```
write_to_file .claude.dev/watch_run.patch "
--- a/lib/memo/watch_run.ex
+++ b/lib/memo/watch_run.ex
@@ -1,7 +1,9 @@
 defmodule Memo.WatchRun do
+  @moduledoc """
+  A GenServer that watches for file changes in a specified vault path and triggers
+  export scripts when changes are detected.
+  """
+
   use GenServer
   require Logger
 
-  # delay in milliseconds
-  @unlock_delay 2000
+  @unlock_delay Application.get_env(:memo, :unlock_delay, 2000)
"
\```

Then run the following command with `execute_command`:

\```bash
patch -p1 < .claude.dev/watch_run.patch
\```

Ensure that the patch applies cleanly against the current contents of the file. Double-check line numbers, indentation, and whitespace.
```

Some parts are taken from aider's [unified prompts](https://github.com/paul-gauthier/aider/blob/3995accd0ca71cea90ef76d516837f8c2731b9fe/aider/coders/udiff_prompts.py#L6). YMMV - 700+ LOC will output malformed patches, so feel free to tune the prompt or use it as a point to help Claude refer back to. For these cases, it is better to rely on aider, so I'm hoping for a unified_diff_write tool that we can deprecate once limits on output tokens disappear.

**Comment by vtempest** [comment]
https://github.com/saoudrizwan/claude-dev/releases/tag/v1.5.6
Does this attempt to fix the issue?

**Comment by saoudrizwan** [comment]
@vtempest yes! pls see the update at the bottom of [this comment](https://github.com/saoudrizwan/claude-dev/issues/14#issuecomment-2283482762).

**Comment by DrugsAreMyLife** [comment]
Rather than asking Claude to provide me with the entire contents of the file back or just the parts of the code that changed, I'll specifically ask for the entire function to be returned for any modified functions. This helped substantially with token usage and my ability to quickly know where code is supposed to go when I'm doing it manually. I feel like it's one zoom level out from "just the code that's changed".

**Comment by joegiglio** [comment]
How is everyone feeling about the published fix?  Are we back in business?  Any gotchas? 

I had moved over the Cursor but that has its own set of problems!  :)

**Comment by kunwarVivek** [comment]
I still see the code getting overwritten with placeholders :(

**Comment by kirill578** [comment]
Can confirm. I am able to reproduce by asking it to modify claude-dev.

**Comment by vtempest** [comment]
**Feature Idea:** Have an input in the settings for custom system level instructions, which is a great feature of Cursor Editor your lead competitor.

> 
"Generate complete, untruncated code without omissions. Include all necessary details, imports, and full function/class implementations. Do not use ellipses (...) or comments like 'rest of code here' to abbreviate. Provide the entire requested code in full."

**Comment by saoudrizwan** [comment]
For anybody that faces this issue, Anthropic will be releasing a new fast edit mode that should fix this–it will help claude easily output tokens he's already read, in other words editing files will be much faster and less `//rest of code here` (+ hopefully cheaper). 

In the meantime, I've created a wiki to help work around this issue: https://github.com/saoudrizwan/claude-dev/wiki/Troubleshooting-%E2%80%90-Claude-Deleting-Code-with-%22rest-of-code-here%22-Comments

**Comment by napter** [comment]
@saoudrizwan first off, thank you for this incredible tool.

In the latest version, these issues still happen quite often. It would be really useful if you could have "// rest of code here" sections automatically get swapped for the contents. Often there is a lot of copy/pasting required since // rest of code here gets combined as an deletion + insertion in the UI.

Alternatively, I don't know if this is possible but perhaps the diff can be modified so that any "// rest of code here" sections are always stand alone deletions and never combined as a single change with additions. 

If "// rest of code here" could be automatically swapped then it might actually be **better** to request Claude output those and reduce useless output tokens. Maybe it could be prompted to include a special output for these deletions including line numbers.

**Comment by peterforeman** [comment]
I'm having a hard time working with Claude and cline. It's almost unworkable currently because of the truncations. This was better before :-(

**Comment by vtempest** [comment]
> I'm having a hard time working with Claude and cline. It's almost unworkable currently because of the truncations. This was better before :-(

Try adding to each prompt: Print out all lines of the file even if not modified. Do not omit any code and do not say "rest of code here"

**Comment by joegiglio** [comment]
I don't think this one should be marked as Closed. It is a huge bug, regardless of the cause.  Suggested workarounds don't seem to work consistently, if at all.

**Comment by dylantovey99** [comment]
I am finding myself in endless truncation loops as well e.g. you tell it to restore truncation and it truncates somewhere else. Having an easy option to revert "rest of the code" blocks would be a good workaround.

**Comment by vtempest** [comment]
Yes we should vectorize the lines to see which ones from the original to use to fill in the "rest of the code here" blocks. You can code this with regex, hf transformers, and airesearch.js.org
