### ISSUE TITLE
Getting it working with Azure OpenAI endpoints?

### ISSUE THREAD

**Issue by regstuff** [saoudrizwan/claude-dev#216]
Hi
I know it's called claude-dev, :) but I get free credits from Azure's cloud plan, and wanted to use that.
I tried setting it up via the openai compatible endpoint option, but it doesn't seem to be working.
Any advice on how this could be set up?

**Comment by Expro** [comment]
Doesn't work with Ollama as well.

**Comment by invalidname1911** [comment]
yea, it just say model does not support tools

**Comment by saoudrizwan** [comment]
@regstuff can you pls show what errors you were seeing? also what model are you trying to use (claude dev won't work with every model ie if it doesn't support tools)

**Comment by saoudrizwan** [comment]
@Expro what model are you trying to use?

**Comment by regstuff** [comment]
@saoudrizwan 
I'm using gpt-4o. I get 404 Resource not found error.
Base url (have removed some details): https://<resourcename>.openai.azure.com/openai/deployments/<deploymentname>/chat/completions
model id is gpt-4o (also the name I have deployed with on azure)
Have tried various permutations of base url (eg removing the chat/completions from the url etc) and model-id but no luck.

**Comment by Expro** [comment]
> @Expro what model are you trying to use?

llama3.1 8B, but I don't think that matters, I was getting 404. Ollama itself runs well, I have it integrated with 2 other projects, so issue is on Claude Dev side.

**Comment by saoudrizwan** [comment]
@Expro can I see what your settings looks like? you need to select ollama as your api provider and then make sure the model id is input correctly. if your api url is different than the default http://localhost:11434 then you'll need to select 'openai compatible' as your api provider and add your url there and 'ollama' for the api key.

**Comment by Expro** [comment]
I no longer have extension installed, but configuration had correct address (verified manually with curl) and API key was indeed "ollama".

**Comment by krishnaprasanthg** [comment]
@regstuff @Expro I was able to use this https://github.com/stulzq/azure-openai-proxy as a docker instance to proxy the requests to azure openai instance. Except that the Base URL should look like "http://127.0.0.1:8080/v1". It seems claude-dev doesn't pass the "v1" in the uri path.

**Comment by ironerumi** [comment]
I also tried to connect to azure openai, but I always get "404 Resource not found".
Inspired by @krishnaprasanthg , [litellm](https://docs.litellm.ai/docs/proxy/deploy) a a proxy works me as well, but keeping a container running just for this is not ideal.

**Comment by wyun** [comment]
yes, same issue here. I got 404 error as well.  

I could get it working with Continue.Dev using this configuration, maybe 'ClaudeDev' needs to add the 'api version'. 

`    {
      "model": "gpt-4o",
      "contextLength": 128000,
      "title": "GPT-4o",
      "systemMessage": "You are an expert software developer. You give helpful and concise responses.",
      "apiKey": "-----------------",
      "engine": "gpt-4o",
      "apiBase": "https://deployment_id_by_user.openai.azure.com/",
      "apiVersion": "2024-02-15-preview",
      "apiType": "azure",
      "provider": "azure"
    }`

**Comment by thunderbug1** [comment]
I have the same problem:
API Request Failed
404 Resource not found

The settings (baseurl and api key) are definitely correct since they work if I use them in python code with the openai package.

I think @wyun might be right that the apiVersion needs to be added for azure openai api calls.
This is the [expected api url](https://learn.microsoft.com/en-us/azure/ai-services/openai/reference#rest-api-versioning)

**Comment by Ethan-Otto** [comment]
I keep getting invalid url even for standard open ai calls
![image](https://github.com/user-attachments/assets/c422676b-42e9-4dce-b877-bad5a78b4eca)

**Comment by falwickster** [comment]
I think the underlying issue is that claude-dev uses openai provider class. 

https://github.com/saoudrizwan/claude-dev/blob/3b61b05c834eb279e561f86b52d6db3cf4ad4ec7/src/api/openai.ts#L7

In openai dependency I see that they recommend using different class for microsoft azure openai, due to slight API differences

https://github.com/openai/openai-node?tab=readme-ov-file#microsoft-azure-openai

So I think someone needs to open a pull request, and add another handler for Microsoft Azure Open AI, and make another option in API Provider dropdown list

**Comment by dodyw** [comment]
> @regstuff @Expro I was able to use this https://github.com/stulzq/azure-openai-proxy as a docker instance to proxy the requests to azure openai instance. Except that the Base URL should look like "http://127.0.0.1:8080/v1" in claude-dev extension. It seems claude-dev doesn't pass the "v1" in the uri path.

thank you, I manage it work today, using proxy, installed as docker, then add /v1 in the base url.

**Comment by saoudrizwan** [comment]
@falwickster thank you for finding this, I will add this asap!

**Comment by saoudrizwan** [comment]
v1.6.5 now supports azure openai, you should still use 'openai compatible' and it will detect if it's an azure endpoint. Pls let me know if you run into any issues!

**Comment by kavin851018** [comment]
> v1.6.5 now supports azure openai, you should still use 'openai compatible' and it will detect if it's an azure endpoint. Pls let me know if you run into any issues!

i still get 404 Resource not found

**Comment by Palkers76** [comment]
I also have this error

**Comment by jirwin79** [comment]
I get a 400 status code (no body) error. trying to use llama 405b from an azure ai endpoint.

**Comment by specter119** [comment]
> v1.6.5 now supports azure openai, you should still use 'openai compatible' and it will detect if it's an azure endpoint. Pls let me know if you run into any issues!

Hi @saoudrizwan seems this issue not solved yet.

**Comment by regstuff** [comment]
It's working fine for me. 
Base URL: https://resourcename.openai.azure.com/openai/deployments/deploymentname/
Model ID: name given in Azure deployments

**Comment by kavin851018** [comment]
still 404
but my endpoint and key can use in anythingllm

**Comment by falwickster** [comment]
Probably that's because apiVersion is hardcoded into AzureOpenAI client. https://github.com/saoudrizwan/claude-dev/blob/afa399e3d72ec994ccb3a9ff9693fb93514b45b6/src/api/openai.ts#L15-L20
That is not correct, we need to have an ability to provide version in input, as we have some control of the apiVersion of deployment to some extent. My deployment has apiVersion=2023-03-15-preview

<img width="473" alt="image" src="https://github.com/user-attachments/assets/158094ce-800e-461f-816a-947016acb8db">

From looking on other tools like Aider or Continue, Azure Open AI is configurable separately from Open AI. 

In Aider configuration for Open AI vs Azure Open AI
https://aider.chat/docs/llms/openai.html
https://aider.chat/docs/llms/azure.html

**Comment by saoudrizwan** [comment]
Just now seeing this, sorry it's been hectic! Thank you for looking into this @falwickster

**Comment by saoudrizwan** [comment]
Thank you for your patience, was on the grind getting the last context mentions update out. I just released v1.8.1 that lets you set the Azure API version. Pls LMK if this fixes the issues you guys were having.

![image](https://github.com/user-attachments/assets/94986026-4f5c-4638-8df5-230e74a5fe2c)

**Comment by doubianimehdi** [comment]
Sorry but still not working ... same error 404 even with the API version ...

**Comment by falwickster** [comment]
For me it's working 

@doubianimehdi remember that base URL should look like this: https://your-resource-name.openai.azure.com/openai

@saoudrizwan I had a pull request with input for API version. I will close it

**Comment by nmahajanoii** [comment]
> It's working fine for me. Base URL: https://resourcename.openai.azure.com/openai/deployments/deploymentname/ Model ID: name given in Azure deployments

This is correct config and it is working

**Comment by bodzebod** [comment]
Hi, I get an error 404 when trying to set up an access to gpt-4o in my company private AzureAI deployment. The URL domain is slightly different from public deployments as the domain ends with "azure-api.net", not "azure.com".
The full URL looks like that: 
https://XXXXXXXX.azure-api.net/openai/deployments/gpt-4o/chat/completions?api-version=2024-02-01

So, I tried to set the base URL to https://XXXXXXXX.azure-api.net/openai, with the API key, model id "gpt-4o" and the API version. But it returns 404 not found.
I even tried a trick to add a custom entry in my hosts file to resolve XXXXXXXX.azure.com instead of XXXXXXXX.azure-api.net, but it didn't change anything.

**Comment by xkong2017** [comment]
Our endpoint is like below: https://{{ressource_id}}.openai.azure.com/openai/deployments/{{deployment_id}}/chat/completions?api-version={{azure_api_version}}

We tried to directly copy the url, key to the extension, but still not work

**Comment by shrijayan** [comment]
When I try to use Azure GPT-4

Cannot read properties of undefined (reading 'type')

**Comment by James4Ever0** [comment]
The API says token limit exceeded. Can one manually edit the context window or truncate the context automatically? Also either query or specify the context limit before sending requests.

**Comment by mcasalaina** [comment]
Hello from Azure! I'm sorry to say that setting up Cline with Azure OpenAI is still clear as mud.

The expected setup looks like this:

![Image](https://github.com/user-attachments/assets/4bfd821d-8ac2-4f4d-82f8-4d1db9fb8aea)

(this is indeed a working endpoint and key, I use it all the time)

I finally got it working by setting my base URL to https://mcasalaina-asts.openai.azure.com/openai/deployments/gpt-4o-2024-11-20, but that's not how you normally do things with Azure OpenAI. I should just be able to specify the endpoint as https://mcasalaina-asts.openai.azure.com and it should be able to construct the rest of the URL from that.

**Comment by federel** [comment]
Any progress to make Azure OpenAi configuration easier?
Thanks.
