### ISSUE TITLE
PRs incoming

### ISSUE THREAD

**Issue by Balatzar** [saoudrizwan/claude-dev#23]
Hello! First I would like to congratulate @saoudrizwan for this wonderful extension, it works really well and has replaced Cursor and Continue in our workflow!

But we would like to see a few features to really make it the best copilot possible :
- Auto-approuve (say Yes automatically to specific tasks)
- Recover after crash (for instance when the claude API times us out, we have to recreate the full task, which is frustrating)
- List previous tasks (history)

We are going to work on these with @loicboutet, but if there are already people working on them we would love to help :)

**Comment by CiberNin** [comment]
for auto-approve, are you implying a whitelist? Maybe one that allows regex for flexibility?

**Comment by jadams777** [comment]
I love Claude Dev, but I keep hitting the daily token limit in 1-2 hours of using it. Then it's dead for the next 24 hours, so I have to switch to Aider. 

Please add support for a backup LLM, e.g. DeepSeek Coder V2 0724. It's ranked second on Aider's leaderboard. 
https://aider.chat/docs/leaderboards/

**Comment by CiberNin** [comment]
Alternate or supplemental solution is to figure out ways to get similar performance while minimizing token usage. For instance feeding in entire project in a single round instead of having it set one file then fetch the next file while keeping the first file in contact and so on. 

Also use smaller faster cheaper models to do first level inference. For instance you could have a model that is zero shot prompted to decide if a task is complex enough to require the full sonnet.

**Comment by saoudrizwan** [comment]
Hey sorry for the late reply, it's been a busy couple weeks! @Balatzar thank you for making that contribution early on, I wasn't ready to accept your pr at the time bc it refactored so much and I had 3+ stashes I did not want to break. If it's any consolation, v1.3.0 now has task history!

**Comment by Balatzar** [comment]
No problem, you've been very efficient, thank you very much for all the updates you made :) The project analyser is very cool and the caching is extremely promising!

Thank you for the task history! What do you think about making an auto-approuve option? 👀 especially now with the cost-reducing caching!
