### ISSUE TITLE
Info: Best LLM for Claude DEV "GPT4o-mini"

### ISSUE THREAD

**Issue by mikekaldig** [saoudrizwan/claude-dev#251]
Hello everyone, first of all, a big thanks to the developer for this amazing plugin for Visual Studio Code. The plugin works even better than something like "open devin" or "devika."

Now for the rest: I've integrated GPT4o-mini, and the cost per prompt is only around 1-5 cents. This is a very affordable way to do web development. I hope this might help someone out there.

I had tried using local LLMs on a P40, but it barely worked, if at all. And with API costs being around $1-2 per day, the electricity cost for running a local LLM is probably higher than just using GPT4o-mini.

Best regards,
Mike

**Comment by cosmix** [comment]
The cost of Claude Sonnet 3.5 is very similar (1-5cents) and its performance, compared to GPT4o-mini _vastly_ superior, in my experience.

**Comment by pietz** [comment]
@cosmix Sonnet is a lot better but also 20x more expensive.

**Comment by dodyw** [comment]
I created a similar app using Sonnet 3.5 and GPT-4o, the results from Sonnet are far better, and it can offer much better than what I expected before.

While GPT-4o, sometimes produces errors and loops forever. Not only that response from GPT-4o seems to be lazy, for example when creating a page it only creates a placeholder, when designing a database table, it only produces minimalistic, while Sonnet 3.5 looks to be made by an experienced developer with complete data fields. So it saves time and money since I do not need to instruct it again to fill them.

However sonnet seems to fail to break down too complex / too many cases at once, so I as an operator need to help it to break down the task into smaller ones.

**Comment by cosmix** [comment]
@pietz The point I’m making here is with regard to the 1-5¢ mention for GPT4o-mini. In my use of Claude Dev with Sonnet 3.5, I’m getting around 1-5¢ per API request, not 20¢-$1 (that the price-list derived 20× multiple would imply.) — which makes no sense to me. And that’s setting aside the very obvious quality/performance angle that @dodyw mentions in the comment above.

**Comment by pietz** [comment]
I just wanted to add information because the conversation the two of you were having about costs wasn't helpful. Needing a certain amount for a request is subjective, while the cost ratio between models is objective.

I certainly agree with your quality estimate. GPT-4o-mini is a much cheaper and much less capable alternative.

OP shouldn't have opened this as an issue.

**Comment by cosmix** [comment]
A range of cost per API call is not subjective. That’s why it’s a *range*. It should encompass different conditions that may affect the cost. Which is why I commented in the first place, as I found it strange. Anyhow, I agree with everything else.

**Comment by asdf8675309** [comment]
I found the cost of sonnet with the query cache to be similar to gpt-4o-mini.  While the initial calls are more on sonnet the use of the query cache (TTL of 5 minutes) works great.  
Once my query's start to cost about 5 cents per query, I typically start a new task.  That resets the input window.  On the anthropic dashboard I can see the queries hitting 100k-150k input tokens per query when it starts to cost 5cents or more.  
I've had good luck asking claude-dev to create a prompt.txt file that contains the history and summary of what we were working on to pick it up at a later date.

**Comment by Cally99** [comment]
@asdf8675309  how much is this costing you per day with those techniques now?

**Comment by asdf8675309** [comment]
When working with C#/.NET/Blazor it seemed to be $3-$4 per hour.  Working with some node/js/tyscript stuff - closer to $2/hour.  If you are consistent and can make use of the query cache, then it works out great.
