### ISSUE TITLE
Error Claude tried to use read_file without value for required parameter 'path'. Retrying...

### ISSUE THREAD

**Issue by shyuck** [saoudrizwan/claude-dev#264]
I keep getting that error when using gemini 1.5 flash. I have a project I was working on with sonnet 3.5 but I cant work on it with flash because of this error.

**Comment by saoudrizwan** [comment]
This happens when the model has a hard time recreating your entire file. I suggest updating to v1.6.3 as I've adjusted the error response when this happens and the model will try to reduce its response size into smaller files for example.

Closing as it's not something I can fix, but anthropic's releasing fast edit mode soon that should pretty much all but fix this issue.
