### ISSUE TITLE
Please update the model for the openrouter, there is now official sonnet not the beta (OpenRouter)

### ISSUE THREAD

**Issue by ham-zax** [saoudrizwan/claude-dev#281]
![image](https://github.com/user-attachments/assets/c1034261-7114-4a91-9b53-951dd50fede0)
as shown in the image the beta model is now called Claude 3.5 Sonnet (self-moderated)
and there is a normal sonnet 3.5
and i have compared it, and it seems like it improves the response, The code is well-organized, readable, and maintainable, with clear separation of concerns.
so please update

**Comment by chatchatgpt** [comment]
+1
waiting for it

**Comment by saoudrizwan** [comment]
The extension uses the self-moderated version, from openrouter's site: "This is a faster endpoint, made available in collaboration with Anthropic, that is self-moderated: response moderation happens on the provider's side instead of OpenRouter's."

Also v1.6.7 now adds prompt caching to openrouter! (You won't be able to see the cached # of tokens, but the API cost will be accurate)
