### ISSUE TITLE
THANK YOU <3

### ISSUE THREAD

**Issue by desaway** [saoudrizwan/claude-dev#309]
This project is awesome. Thank you for all your huge work and the constant updates. I just wanted to tell you that.

Sorry for the issue!

**Comment by rpuls** [comment]
+1 this extension is amazing! 🤯 makes copilot feel like "a 1 year ago discontinued project"

One (probably simple) additional feature could take this extension to the next level...:

Instead of just starting a task with a prompt, it would be insanely useful with a little more setup to shape the task definition.

New task:

1. Task description
2. (optional) Select file to use as template/example  (i.e. a UI component _of my choice_ that is similar to what I need current task to generate - or a unit test _of my choice_ when a task is about generating new tests)
3. (optional) Be able to force include other files for additional context (i.e. link to my datamodel.definition.js, or link to task-relevant-helper-lib.js)

**Comment by saoudrizwan** [comment]
> This project is awesome. Thank you for all your huge work and the constant updates. I just wanted to tell you that.

Thank you @desaway ❤️ It's comments like this that made my decision to work on this project full-time worth it.

**Comment by saoudrizwan** [comment]
> Instead of just starting a task with a prompt, it would be insanely useful with a little more setup to shape the task definition ... Be able to force include other files for additional context

Currently working on an update that I think will make you very happy! 😄
