### ISSUE TITLE
Ability to disable the auto-linting fixes

### ISSUE THREAD

**Issue by bradam12** [saoudrizwan/claude-dev#310]
The auto-linting changes in 1.7.0 are awesome, but I'd like to have them toggleable in certain cases where I'm performing specific tasks.

For example I may have open tabs for unrelated files, or a notes file that has linting errors since vscode erroneously detected the wrong autoformat. 

Of course I can (and have) asked Claude to skip via `Ignore any linting errors or warnings provided by VSCode Workspace Diagnostics` and it works, but it still takes up tokens in the request.

**Comment by saoudrizwan** [comment]
Hey thanks for taking the time to make the issue. I just released v1.7.3 that now only uses workspace errors (and not warnings since this may be too distracting in large projects). I've also added the following instructions to the system prompt:
- You will automatically receive workspace error diagnostics in environment_details. Be mindful that this may include issues beyond the scope of your task or the user's request. Focus on addressing errors and warnings relevant to your work, and avoid fixing pre-existing or unrelated issues unless the user specifically instructs you to do so.
- If you are unable to resolve errors provided in environment_details after a few attempts, consider using ask_followup_question to ask the user for additional information, such as the latest documentation related to a problematic framework, to help you make progress on the task.

Please give the new update a go and let me know how it works for you.

**Comment by saoudrizwan** [comment]
@bradam12 Please see this comment: https://github.com/saoudrizwan/claude-dev/issues/319#issuecomment-2356375137
