### ISSUE TITLE
Create option for including/excluding input from the "Problem tab"

### ISSUE THREAD

**Issue by AndyMik90** [saoudrizwan/claude-dev#315]
In some cases, the problems defined in the "problems" tab for bigger projects are not always defined to the task Claude Dev is trying to solve.

Making this a optional feature that can be toggled on/off would be more suitable for very large projects.

**Comment by saoudrizwan** [comment]
Hey thanks for taking the time to make the issue. I just released v1.7.3 that now only uses workspace errors (and not warnings since this may be too distracting in large projects). I've also added the following instructions to the system prompt:
- You will automatically receive workspace error diagnostics in environment_details. Be mindful that this may include issues beyond the scope of your task or the user's request. Focus on addressing errors and warnings relevant to your work, and avoid fixing pre-existing or unrelated issues unless the user specifically instructs you to do so.
- If you are unable to resolve errors provided in environment_details after a few attempts, consider using ask_followup_question to ask the user for additional information, such as the latest documentation related to a problematic framework, to help you make progress on the task.

Please give the new update a go and let me know how it works for you.

**Comment by AndyMik90** [comment]
Great work @saoudrizwan will test it out now.
