### ISSUE TITLE
Gemini not reading files

### ISSUE THREAD

**Issue by asdf8675309** [saoudrizwan/claude-dev#332]
I set up keys for Gemini and have tried with both the flash and pro model.

Sometimes it will read the files and content correctly, but sometimes it says that it can't read the files and doesn't have permission.  
It has happened with both the flash and pro model.  

I can then switch the provider to anthropic and it works right away.

**Comment by abeusher** [comment]
I'm experiencing the same behavior with Gemini Flash 1.5

**Comment by saoudrizwan** [comment]
Claude Dev doesnt work great with weaker models unfortunately. I originally made the extension to only work with claude 3.5 sonnet since that was the only model I found reliable enough to do both tool calling and autonomous loop prompts–even asking other large models like mistral didnt work out great. So it's expected models like flash 1.5 won't work as expected sometimes. It's only a matter of time before these models get better, but for now not much I can do about this, I am sorry
