### ISSUE TITLE
Deepseek2 does not support K-shift

### ISSUE THREAD

**Issue by 6313504** [saoudrizwan/claude-dev#343]

**Comment by saoudrizwan** [comment]
Claude Dev doesnt work great with most local models unfortunately. I originally made the extension to only work with claude 3.5 sonnet since that was the only model i found reliable enough to do both tool calling and autonomous loop prompts–even asking other large models like mistral didnt work out great. So it's expected local quantized models wont work the best, but ive found most success with llama3.1 70b although it struggles if you dont give it a clear and specific prompt. Hopefully local models keep getting the same attention and we have claude 3.5 sonnet level models on ollama in a few years. For now not much I can do about this though, I am sorry
