### ISSUE TITLE
Problem using the model in Ollama

### ISSUE THREAD

**Issue by wwjj999** [saoudrizwan/claude-dev#345]
"Your program is very well developed, and it will be a great piece of work. However, I still have some questions to raise. For instance, in the current version, after selecting the model in Ollama, it doesn't work properly like Claude. It keeps asking for the project directory, regardless of whether you're already in an empty directory or whether you've told it to create a new one—none of these work. I am using the Qwen 2.5 model from Ollama. I'm not sure what causes this issue, and while I don't care much about the reason, you should provide a solution or update it in the next version. Thank you very much, and I hope your work continues to improve."

**Comment by awesomecoolraj** [comment]
having the exact same issue over here

**Comment by suzuke** [comment]
the same here

**Comment by CiberNin** [comment]
Could we get some specific API logs?

**Comment by saoudrizwan** [comment]
Claude Dev doesnt work great with most local models unfortunately. I originally made the extension to only work with claude 3.5 sonnet since that was the only model i found reliable enough to do both tool calling and autonomous loop prompts–even asking other large models like mistral didnt work out great. So it's expected local quantized models wont work the best, but ive found most success with llama3.1 70b although it struggles if you dont give it a clear and specific prompt. Hopefully local models keep getting the same attention and we have claude 3.5 sonnet level models on ollama in a few years. For now not much I can do this about though, I am sorry

**Comment by hhao** [comment]
ollama run [hhao/deepseek-coder-v2-lite-tool](https://ollama.com/hhao/deepseek-coder-v2-lite-tool)

you can run this model  with Claude Dev.

**Comment by prod2zzr** [comment]
> ollama run [hhao/qwen2.5-coder-tools](https://ollama.com/hhao/qwen2.5-coder-tools)ollama 运行 hhao/qwen2.5-coder-tools
> 
> you can run this model with Claude Dev.您可以使用 Claude Dev 运行此模型。

thx, how did you fine-tune the model that can work with Cline? awesome!

**Comment by daaku** [comment]
@hhao any chance you could share your fine tuning process? Updated model weights just came out today:

https://www.reddit.com/r/LocalLLaMA/comments/1glfzyl/qwen_25_coder_7b_15b_instruct_models_just/

**Comment by hhao** [comment]
> @hhao any chance you could share your fine tuning process? Updated model weights just came out today:
> 
> https://www.reddit.com/r/LocalLLaMA/comments/1glfzyl/qwen_25_coder_7b_15b_instruct_models_just/

Look at this: #95 
Qwen2.5 is more powerful than deepseek-coder-v2-lite

**Comment by daaku** [comment]
Ah! I _assumed_ there was fine tuning involved. It's a custom prompt but the original weights? Also I agree, I've found Qwen2.5 is better than deepseek-coder-v2-lite.
