### ISSUE TITLE
Infinite loop

### ISSUE THREAD

**Issue by phalexo** [saoudrizwan/claude-dev#349]
I was just trying to test Claude-Dev with Ollama/Meta-LLama-3.1-70b-Instruct.Q5_M. 

I have one file in the folder sliding.py with some Python code. The python is 3.11.9 in a conda environment.

My prompt was "Check for errors in @/sliding.py"

I can see the GPUs doing something.

The MSCODE which is running the Claude-Dev extension tries/reads the file.

Sends a whole lot of tokens to the model

And then goes back to trying to read the file.

Again, and again, with number of tokens growing and growing, got above 50000.

**Comment by saoudrizwan** [comment]
Hey sorry you experienced this, but quantized llama models dont work great with claude dev. They don't tool call correctly and have a hard time with autonmous loop prompting, so it's hard for me to tell you I can fix this somehow. The extension was originally made to only work with claude 3.5 sonnet because that was the only model I had reliable results with. I suggest using that for complex problems and ollama for really simple basic tasks. Although I hope in the future we'll have much more capable local models available!
