### ISSUE TITLE
Allow switching models in an already existing task

### ISSUE THREAD

**Issue by ALMaclaine** [saoudrizwan/claude-dev#351]
Allow switching models in an already existing task

I think this would be useful not only for when you are rate limited, but if you want to swap to a more advanced model for some tasks.

**Comment by CiberNin** [comment]
I've never had issues doing this? Well sometimes it seems to reset if you change the setting mid thinking, but otherwise I've swapped back and forth in settings to avoid limits quite often.

**Comment by saoudrizwan** [comment]
You can already switch models mid task, just open settings and change the model. Although you'd need to be using the sidebar version of the extension for it to update in an active task. I'm considering adding a models option to the `@` context menu, so stay tuned for that! Closing this issue bc I'd like ideas to be added to our Ideas board so ppl can vote on their favorite ones: https://github.com/saoudrizwan/claude-dev/discussions/categories/ideas

**Comment by lee-b** [comment]
This sort of works without entering the details, if you've already entered two different types of provider and just want to switch between them in the settings.  For example, I can switch between claude and a local model without re-entering urls etc.  It would be nice to support this properly though, with multiple named providers and their own connection type and settings, and the ability to select the current provider name in the chat/main view rather than the settings.
