### ISSUE TITLE
[Bug]: Probably a folder or file permission issue?

### ISSUE THREAD

**Issue by topmask** [saoudrizwan/claude-dev#359]
### Which API Provider are you using?

Ollama

### Which Model are you using?

qwen2.5-coder:1.5b

### What happened?

Claude wants to view the top level files in this directory:
Claude wants to view the top level files in this directory:
Claude wants to view the top level files in this directory:

### Steps to reproduce

[list_files]
1.html

<environment_details>
# VSCode Visible Files
../trigger/1.html

# VSCode Open Tabs
../trigger/1.html
</environment_details>

### Relevant API REQUEST output

```shell
There may be a problem with folder or file permissions
```

### Before you submit

- [X] I have checked existing issues
- [X] I am using the latest version of Claude Dev and VSCode

**Comment by saoudrizwan** [comment]
Claude Dev doesnt work great with most local models unfortunately. I originally made the extension to only work with claude 3.5 sonnet since that was the only model i found reliable enough to do both tool calling and autonomous loop prompts, even asking other large models like mistral didnt work out great. So it's expected local quantized models wont work the best, but ive found most success with llama3.1 70b although it struggles if you dont give it a clear and specific prompt. Hopefully local models keep getting the same attention and we have claude 3.5 sonnet level models on ollama in a few years. For now not much I can do this about though, I am sorry

**Comment by wangqj** [comment]
The same issue, how to resolve it?
