### ISSUE TITLE
[Bug]: API Request Failed

### ISSUE THREAD

**Issue by arpo** [saoudrizwan/claude-dev#364]
### Which API Provider are you using?

Anthropic

### Which Model are you using?

Claude 3.5 Sonnet

### What happened?

I do get this error quit frequently when running my tasks. 
529 {"type":"error","error":{"type":"overloaded_error","message":"Overloaded"}}

### Steps to reproduce

1. Creating a task in VS code for Claude 3.5 Sonnet
2. Running through some steps
3. This is the last prompt to the claude-dev
```
[write_to_file]
The content was successfully saved to src/components/EngineView.tsx.

<environment_details>
# VSCode Visible Files
src/components/EngineView.tsx

# VSCode Open Tabs
src/components/Hiber3D/Hiber3DApi.tsx
src/components/EngineView.tsx
src/utils/math/quaternionFromNormal.ts
src/components/Hiber3D/utils/rayCastFromScreen.ts
</environment_details>
```
...

### Relevant API REQUEST output

```shell
529 {"type":"error","error":{"type":"overloaded_error","message":"Overloaded"}}
```

### Before you submit

- [X] I have checked existing issues
- [X] I am using the latest version of Claude Dev and VSCode

**Comment by ichoosetoaccept** [comment]
+1 here for this one. My Claude Dev extension is stuck in this state and always returns this API response.
At console.anthropic.com under Logs, I can see these failing requests:
![CleanShot 2024-09-23 at 17 54 12@2x](https://github.com/user-attachments/assets/21571bba-26ab-4bf3-9343-6e76dbd9c1c2)
Interestingly, there it says "client error", suggesting that the problem might be on the client-side (meaning me or the Claude Dev extension, respectively), rather than Anthropic's API Endpoint.

Mentioning that in case it helps.

**Comment by sumith** [comment]
That is an issue with Anthropic.  You get that issue with any tool you use and it generally gets resolved after a few minutes.  There has been a degradation of response today as reported by Anthropic Status page.

**Comment by saoudrizwan** [comment]
529 means Anthropic servers down, I suggest using OpenRouter in the meantime–they have prompt caching now and better rate limits!
