### ISSUE TITLE
"Claude viewed the top level files in this directory" runs infinitely.

### ISSUE THREAD

**Issue by MrZero7** [saoudrizwan/claude-dev#385]
### Which API Provider are you using?

Ollama

### Which Model are you using?

Qwen2.5-coder 7b

### What happened?

 Hi guys,

whenever I try to use claude dev it gives me infinite loop and does not output anything.

I am using claude dev version 1.9.4, vscode and Qwen2.5-coder 7b with ollama on Pop os

ps: I tried everything. I tried loading an older version of claude dev, I tried using other models like llama 3.1 8b and Qwen2.5 14b and nothing. 

### Steps to reproduce

1. create a directory (I called it "test")
2. create a python file in the directory (I called it "test.py")
3. put code in it (I created the game snake and I put it in the file)
4.  while the file is open on vscode I mentioned the file using the new "@" tool
5. I asked claude dev to comment the code
6.  it gives infinite loop saying "Claude viewed the top level files in this directory"

![Screenshot from 2024-09-24 18-17-58](https://github.com/user-attachments/assets/2efc0a4e-4e0d-40aa-870e-9d6c87ab40d0)

**Comment by saoudrizwan** [comment]
Claude Dev doesnt work great with most local models unfortunately. I originally made the extension to only work with claude 3.5 sonnet since that was the only model i found reliable enough to do both tool calling and autonomous loop prompts–even asking other large models like mistral didnt work out great. So it's expected local quantized models wont work the best, but ive found most success with llama3.1 70b although it struggles if you dont give it a clear and specific prompt. Hopefully local models keep getting the same attention and we have claude 3.5 sonnet level models on ollama in a few years. For now not much I can do about this though, I am sorry

**Comment by MrZero7** [comment]
It's okay. Thanks for your great work tho <3
