### ISSUE TITLE
API request hangs sometimes

### ISSUE THREAD

**Issue by oschettler** [saoudrizwan/claude-dev#41]
Thank you for this incredible extension.

I sometimes have the problem that an API request hangs (may be due to rate limit or unreliable internet connection) and there seems no way to cancel it manually or have it timeout.

<img width="327" alt="SCR-20240802-izam" src="https://github.com/user-attachments/assets/350867ab-020c-47eb-bb91-798c5315e82d">

It would be nice if I could either manually interrupt a hanging API request or if requests would timeout automatically.

**Comment by saoudrizwan** [comment]
Anthropic's API can be slow sometimes, or it could be that Claude is coming up with a big response like a new file/change. I've been giving thought as to how I'd implement streaming Claude's response instead of waiting for the whole response at once. But currently working on OpenRouter and Bedrock support for when Anthropic API is slow.
