### ISSUE TITLE
Doesnt stay in working directory

### ISSUE THREAD

**Issue by jtac** [saoudrizwan/claude-dev#44]
When working in a windows environment, it looks like Claude Dev gets stuck under AppData in the VS Code data directory and has to 'cd' into the project directory every time it executes a command:

cd c:\Users\john\project && python manage.py migrate

Together with the problem of executing things outside the virtual environment, this makes for a bit of a mess.

**Comment by saoudrizwan** [comment]
This is expected behavior since claude doesn't have a current working directory when executing commands. I've thought about making the cwd your workspace path, but I found Claude would get confused when trying to interact with directories outside your project i.e. on the Desktop. I'm actively working on modifying the systemp prompt to work around this confusion so it's aware of its cwd and also that it can cd out of that cwd to accomplish tasks in other directories.

**Comment by piotrmasior** [comment]
I know it might be a shitty solution, but given we are operating here on data anyway, adding annotation as the comment at the beginning of the every file like "path_to_file" and later instruction as the rule for prompt to respect that will turn understandandig for LLM where the current context is ? Anyway after working with the code you can always do some pre-commit sanity checker craft for removing that annotations to keep code clean anyway (https://github.com/pre-commit/pre-commit)

**Comment by saoudrizwan** [comment]
The latest v1.0.98 now uses relative paths, in other words Claude works within your workspace directory instead of using absolute paths for tools/commands. This way it doesn't have to cd to execute certain commands, and referencing files is a lot less awkward now that it doesn't use the full path anymore. The exception is when you open Claude Dev without a workspace and it defaults to creating projects on the Desktop, since I'd like to keep the user aware of this fallback behavior.

**Comment by jtac** [comment]
The new version works well within the workspace now, thank you!
