### ISSUE TITLE
Error writing file: Cannot read properties of undefined (reading 'endsWith')

### ISSUE THREAD

**Issue by dcutugno** [saoudrizwan/claude-dev#49]
I almost encounter this error everytime

**Comment by DBonacich** [comment]
I also run into this issue consistently. I have not been able to use this extension because of it.

"
Error
Error writing file:
Cannot read properties of undefined (reading 'endsWith')
"

**Comment by IncreaseWebDev** [comment]
Error
Error writing file:
Cannot read properties of undefined (reading 'split')

API Request Complete
$0.0608

<thinking>

I apologize for the continued error. It seems that I'm encountering an issue with the write_to_file function. Let's try to resolve this by breaking down the process. First, I'll read the current content of the file, then we'll make the necessary modifications, and finally, we'll attempt to write the updated content back to the file.

Let's start by reading the current content of the sitemap_extractor.js file:

</thinking>

I keep getting all sorts of undefined errors too.

**Comment by AlexanderHel** [comment]
I noticed `Cannot read properties of undefined (reading 'split')` using happens when the file script is large/long

**Comment by saoudrizwan** [comment]
It seems like `fs.readFile` is returning undefined without failing, which is not the expected behavior. Is the file it's trying to edit empty?

I've added a sanity check for when readFile could be returning undefined, please update to v1.0.96 and see if your still keep running into the issue.

**Comment by saoudrizwan** [comment]
Ah so it seems Anthropic's API making tool calls with empty parameters even though I marked them as required in the tool schema. This is likely caused by Claude reaching token limits i.e. when outputting multiple large files. I've added checks for empty parameters and if detected, it automatically triggers a new request to get the missing content. 

Please update to v1.0.98 and let me know if that fixes it for you!

**Comment by DBonacich** [comment]
> Ah so it seems Anthropic's API was making tool calls with empty parameters even though I marked them as required in the tool schema. This is likely caused by Claude reaching token limits i.e. when outputting multiple large files. I've added checks for empty parameters and if detected, it automatically triggers a new request to get the missing content.
> 
> Please update to v1.0.98 and let me know if that fixes it for you!

Hi @saoudrizwan 

It seems that with v1.0.99, the `Cannot read properties of undefined (reading 'endsWith')` issue is resolved, but another issue is presented. Below is the error I'm getting:

`Error
Claude tried to use write_to_file for 'Personal_Claude.py' without value for required parameter 'content'. This is likely due to output token limits. Retrying...`

For context, I have a python script in my workspace named 'Personal_Claude.py' that is roughly 720 lines of code. What I'm asking the AI to do is inspect the code for any errors and optimization opportunities. The conversation from the AI follows as such:

`<thinking>

After analyzing the code, I've identified several areas for improvement and enhancement. Let's address these issues and make the necessary modifications to align the script with the user's goal.

1. Enhance system access capabilities
2. Improve error handling and logging
3. Implement more robust tool execution
4. Enhance the Perplexity API integration
5. Improve the user interface and experience
6. Implement a more dynamic system message
7. Add a function to check and update API keys

Let's start by making these improvements:

</thinking>

Error
Claude tried to use write_to_file for 'Personal_Claude.py' without value for required parameter 'content'. This is likely due to output token limits. Retrying...

API Request Complete
$0.1620

I apologize for the oversight. Let's provide the updated content for the file:

Error
Claude tried to use write_to_file for 'Personal_Claude.py' without value for required parameter 'content'. This is likely due to output token limits. Retrying...

API Request Complete
$0.1623

I apologize for the confusion. Let's provide the updated content for the file:

Error
Claude tried to use write_to_file for 'Personal_Claude.py' without value for required parameter 'content'. This is likely due to output token limits. Retrying...

Making API Request...`

This error continues in a loop. It may have something to do with the length of my script that I am asking it to inspect and modify. But I am able to feed the same script to Claude on the Claude website with no problem.

**Comment by saoudrizwan** [comment]
This is almost certainly due to your file being too large. I'm assuming based off your file's name that you have a system prompt with a lot of text in it, so I recommend extracting that or any other prompts into a separate constants file that you can then import in the script you're trying to edit. Also try changing your provider to Anthropic if it's not already, since it's able to output a max of 8192 tokens while OpenRouter/Bedrock are limited to 4096.

**Comment by saoudrizwan** [comment]
Related to #14, please see [this comment](https://github.com/saoudrizwan/claude-dev/issues/14#issuecomment-2283482762).
