### ISSUE TITLE
Bulk_Read tool

### ISSUE THREAD

**Issue by CiberNin** [saoudrizwan/claude-dev#55]
Give Claude a **Bulk_Read** tool which asks for a list of filepaths that Claude would like to read ordered from most to least desired. 
Will then pass all those files to claude, discarding any files once token limit is exceeded. Obviously when passed each file should be wrapped by markdown codeblock with language & filepath.

To augment Claudes ability to use this tool, the recursive files list tool should provide files sizes in calculated tokens

**Comment by ackoi** [comment]
Would be a great feature to add.

**Comment by saoudrizwan** [comment]
Claude can already make a tool request to read multiple files at once. I've pushed the boundaries of this and I've gotten him to read 6 files at once, but it seems anymore than that might defeat the purpose since he tends to re-read files before editing. I also have to be careful with how many tools I define in the schema since too many tools can affect claude's ability to use the right tools effectively, so I'm gonna close this ticket bc I don't have any plans to add a bulk read tool for now.
