### ISSUE TITLE
Add web search tool to get latest docs for dependencies

### ISSUE THREAD

**Issue by dchuk** [saoudrizwan/claude-dev#57]
When working on a Ruby project for example, you’ll have a Gemfile that lists the libraries for your current project, and you may want to add new gems as well for adding certain functionality.

Ideally, Claude Dev is aware of the current docs for any given library in a project, and either the full docs or the relevant sections of the docs are included in any prompts generated for a user’s requested change.

Do you have a recommended way to make this work well? 

I actually used Claude Dev last night to build a script that accepts a Ruby gem name and generates a single markdown file containing the Readme of the gem, table of contents for all classes and methods, and then all of the RDOC docs for the methods in the gemfile (I took some inspiration from the mutable.ai wiki approach, albeit in a basic initial form. I think these could be even more powerful by using LLMs to generate method descriptions for any weak or missing RDOCs, but not there yet).

Does it make sense to create a /docs folder in my project and put all of these markdown files in it? Is there a way to make sure Claude Dev is aware of those? Or would this be a good feature addition?

My perfect end state would be all gems in my Gemfile automatically get their docs synced to the project I’m working on for Claude Dev to leverage, and even better would also be a way for Claude Dev to discover gems it could use to implement a given feature request, perhaps from an API that accepts a query for use case/functionality and returns a list of gems that could be useful for that.

What do you think?

**Comment by dchuk** [comment]
Yeah agreed there can be a lot of nuance. As a simple starting point though, what are your thoughts on getting Claude Dev to leverage locally stored documents when it’s planning out features? Other AI tools allow you to @ files to be included/prioritized, maybe some concept like that?

**Comment by MusiCode1** [comment]
Maybe it's worth allowing the user to authorize ClaudeDev in some cases, to load the whole project, or a whole folder, into its cache input token memory?

**Comment by saoudrizwan** [comment]
Loading up relevant docs into the initial request to store in the prompt cache for claude to reference throughout the conversation is a great way to effectively fine tune him specifically for your project. There's a lot of ways to go about this but your strategy seems good, create a folder of docs and add Custom Instructions like "read all the files in docs/ when starting the task". I've been considering adding a native docs feature to claude dev, but I have a feeling that this won't be necessary with newer models since they'll be trained on more up to date data. IMO docs RAG the way cursor does it isn't great, and if I were to add a docs lookup tool I'd prefer to take the burden away from the user to have to scrape docs themselves and instead use some sort of 3rd party web search API. Although there's a lot of studies showing how this tends to send LLMs into rabbitholes and distract them from the main task.

**Comment by saoudrizwan** [comment]
Closing as I won't be adding a web search tool for the time being. There's examples showing how web search tools tend to distract models too much from their task as they end up thinking they have to use it just to fact check their world knowledge at every step, often taking them down rabbitholes and getting off track very easily. For now if claude dev needs updated information, you can use the new `@url` context option in the textarea to give him the latest docs for example. If you'd like to see a web search tool added, pls feel free to add it to the ideas board so people can vote on it. https://github.com/saoudrizwan/claude-dev/discussions/categories/ideas
