### ISSUE TITLE
OpenRouter Error: "Invalid JSON response body at https://openrouter.ai/api/v1/chat/completions Reason: Unexpected end of JSON input"

### ISSUE THREAD

**Issue by dcutugno** [saoudrizwan/claude-dev#60]
API Request Failed

invalid json response body at https://openrouter.ai/api/v1/chat/completions reason: Unexpected end of JSON input

**Comment by brianschroeter** [comment]
Same exact issue here, and it's only happening with the OpenRouter provider. Unfortunately I've reached my daily cap with Anthropic, and Bedrock won't let me enable Sonnet 3.5 so I'm kinda stuck.

**Comment by saoudrizwan** [comment]
I've seen this issue today too, but it's not consistent–I can retry the request and it works just fine. It looks like OpenRouter is returning an invalid response to the openai sdk used in the extension. Have you been able to consistently produce this issue with a certain prompt?

**Comment by dcutugno** [comment]
it happen after i approve the read file request and it send to the server waiting for a response i think

**Comment by AyronDevelop** [comment]
> I've seen this issue today too, but it's not consistent–I can retry the request and it works just fine. It looks like OpenRouter is returning an invalid response to the openai sdk used in the extension. Have you been able to consistently produce this issue with a certain prompt?

I have an error when reading or editing files

**Comment by schardosin** [comment]
Same here, sometimes it happens already in the first call, depending of the content being sent through the APIs.
It only happens with OpenRouter, if switching back to Anthropic, it works with no problem, but then we start facing the API limits in Anthropic really fast.

**Comment by dcutugno** [comment]
The problem is Anthropic is only for business

**Comment by saoudrizwan** [comment]
I've been able to get this error consistently by asking Claude to edit a really large file. It turns out that the OpenRouter API responds with invalid JSON when using tools with large enough outputs (in this case the new contents of the file). I suggest switching to Anthropic or AWS Bedrock as they are much more reliable, I've even marked OpenRouter as experimental in the extension so users aren't caught by surprise when they see this error. 

A dirty trick I've found to workaround this problem is switching between different models and retrying the request. I.e. when the request fails, open settings, switch to a different model, hit 'Done' to go back to the task and then hit the retry button to send the same request but to the new model.

**Comment by ChrisChiasson** [comment]
Thank you; this workaround worked for me. I was able to make an Anthropic business key and resume from that point. Confirmed on the large request size (as judged from the request cost being a few times larger than normal). Also confirmed on intermittence--sometimes retrying works with OpenRouter.

**Comment by saoudrizwan** [comment]
I just released v1.1.14 that fixes this issue by using OpenRouter's streaming endpoint as a fallback for when normal requests fail due to invalid JSON. I've reported the issue to the folks at OpenRouter and they are looking into it on their end, but until it's fixed Claude Dev should work as expected.
