### ISSUE TITLE
[FEATURE] Add Support for Embeddings to Reduce Token Usage and Cost

### ISSUE THREAD

**Issue by eprofos** [saoudrizwan/claude-dev#68]
I would like to propose adding a feature that allows the use of an embedding system to reduce the number of tokens in requests. This could help in managing and optimizing the daily token limit, which is currently capped at 1 million tokens per day. By leveraging embeddings, it might be possible to maintain or even enhance functionality while lowering the token usage and associated costs.

This feature would be highly beneficial for users who frequently hit the token limit, as it could provide a more efficient and cost-effective way to utilize the extension.

Thank you for considering this feature request.

**Comment by eprofos** [comment]
I'm not sure if it can help

**Comment by mkearl** [comment]
I have have a revisions.md (rev#.md)  file in my project and have Claud-Dev either create or modify the revisions.md file acordingly..   rev1.md, rev2.md.  and maybe a design.md or process.md file with pertinent information. Then in my prompt I will do something like this.  

Design.md contains The purpose of the project what needs to be acomplished, any design related information, psudo-code and other related project information.

Using the @design.md and @rev1.md I would like you to continue working on blah blah when your complete create a rev2.md file with updated status of the project and next steps.    Then in the next prompt to continue I will do the same but then reference rev2.md instead of rev1.md.  

At times I will do something like this.  Using @design.md, @rev1.md @rev2.md @rev3.md ... make sure that we have implemented such and such.  Provide a new design1.md document so that we can continue going forward. 

I keep my revisions and then if I need to, or it gets lost I can always use the prompt to tell it to go though a certain revision if needed.
It seems to be working fairly well.  Where Claud-Dev can create whatever file I tell it to it makes it nice to be able to handle revisions, document updates etc.


**My actual last prompt I was using:** 
Using the existing solution code, @Design2.md, @Rev17.md as well as the code snippets.  evaluate the solution, the  iterations and existing code base and combine them for the ultimate solution.  When using the existing codebase make sure that the solution uses as much of the existing code as possible in implementing this "feature" implementation.  First act as a code reviewer and find any issues or items that have been missed. Provide a comprehensive list of items that still need to be implemented. Provide any pseudocode or examples that the coder could use. 

Then act as an expert thorough senior coder and use the suggestions from the reviewer to address each item given by the reviewer.  Make code changes and provide the new ultimate solution. For ANY pseudocode that is used within the examples implement the pseudocode.  Provide the complete code from the codebase with the added changes so that I can now add files and changes to the existing solution.  

Using the new code from the Coder and the suggestions from the Reviewer provide an Update that can be added to the design document.

**Comment by mkearl** [comment]
More structured version of the above that I am going to try: 

**Objective:** Evaluate and improve the current implementation of a specific "feature" using the provided solution code and design documents.

**Tasks:**
Code Review and Analysis:

Using the existing solution code, the design documents (@Design2.md, @Rev17.md), and any provided code snippets, perform a thorough code review.
Identify any issues, incomplete implementations, or items that have been missed.
Provide a comprehensive list of all items that still need to be implemented, along with explanations.
Offer pseudocode or examples where necessary to clarify how each issue can be resolved.
Code Implementation:

Based on the findings from the code review, act as an expert senior coder and address each issue raised by the reviewer.
Make the necessary code changes, ensuring that the solution uses as much of the existing codebase as possible to implement the feature.
For any pseudocode provided, implement it within the actual code.
Provide the complete and updated code, integrating all changes so it can be added to the existing solution.
Documentation Update:

Using the new code and the suggestions from the reviewer, draft an update for the design document.
Ensure the update is clear, concise, and reflects all changes made during the implementation phase.

**Comment by saoudrizwan** [comment]
There's no plans to vectorize anything ATM, I've found RAG is pretty ineffective for searching code and I added a few tools that should help claude search a codebase in the most token effective way possible (regex search, source code definitions, etc). Closing this ticket, but if you have specific suggestions for what exactly you want to create embeddings for please let me know.

**Comment by VikashLoomba** [comment]
@saoudrizwan I've recently been exploring using custom embedding models in other tools (specifically Continue.dev) and have found that RAG can actually perform really well with some experimentation. 

Most off-the-shelf RAG performance of other tools like Continue suck, which generally makes the experience using them terrible (especially with OOS models). However I've found surprisingly excellent results from using the jina-embeddings-v2-base-code embedding model with Qwen2.5-Coder-32B as the coding model. The Jina embeddings model has been specifically trained to have semantic understanding of the user query that maps to the code, which makes it perform much better than just using regular text embedding models.

I think experimenting with a RAG pipeline that incorporates something like jina-embeddings-v2-base-code + Repo Maps/AST with Cline could help improve the overall performance, especially for folks like myself that are using locally running models instead of Claude 3.5 sonnet. Even just having a configurable option might make sense.

**Comment by ciekawy** [comment]
RAG ineffective? I found Cline amazing concept and after integrating search/fetch MCPs RAG and memory (aka meta-RAG) is the absolute must have
