### ISSUE TITLE
mass deletion of code "previous next lines unchanged"

### ISSUE THREAD

**Issue by jtac** [saoudrizwan/claude-dev#71]
Here's an example of claude-dev wiping out a lot of code:

```
from django.shortcuts import render, redirect, get_object_or_404
from django.contrib.auth.decorators import login_required
from django.contrib.auth.models import User
from django.contrib.auth import update_session_auth_hash
from django.db import transaction
from django.contrib import messages
from django.db.models import Q, Count
from django.http import JsonResponse
from django.urls import reverse
from .models import Post, Group, Event, Profile, FriendRequest, Message, Comment, GroupPost
from .forms import UserForm, ProfileForm, CustomPasswordChangeForm, GroupForm, EventForm, CommentForm, GroupPostForm

# ... (previous code remains unchanged)

@login_required
def event_detail(request, slug):
    event = get_object_or_404(Event, slug=slug)
    comment_form = CommentForm()
    context = {
        'event': event,
        'comment_form': comment_form,
    }
    return render(request, 'social_network/event_detail.html', context)

# ... (rest of the code remains unchanged)

```

Sometimes the ouput looks like this when the file is quite long, probably to save space, but in the code it causes mayhem :D

The file being edited was 14kb in size.

**Comment by saoudrizwan** [comment]
Yeah this is a [hard problem to solve](https://github.com/saoudrizwan/claude-dev/issues/14#issuecomment-2244433366), it tends to happen for large files due to Claude's output token limitations. I recommend using the Anthropic provider option if you don't already, since it has a max output of 8192 whereas OpenRouter and AWS Bedrock are capped at 4096. You can also try breaking your file down into smaller files. Max tokens are out of my control so I'm gonna close this ticket for now.

**Comment by jtac** [comment]
I actually managed to solve it by instructing Claude not to abbreviate like that. Once I hit the token limit (I use anthropics API) that's a different issue of course.
