### ISSUE TITLE
Code Placeholders that break the whole code

### ISSUE THREAD

**Issue by windy31** [saoudrizwan/claude-dev#81]
Things like:
//this code remains unchanged

That app tries to input, and i have a simple solution to it, if it's possible to implement into plugin.
Make the Claude ai to write out every function that it needs to change, not the whole code.
This way it would write out new functions and the changed ones, the plugin has to find this functions by search and then, change them.

This way we would achieve 2 things:
1) Less tokens for every code change(Since the app doesn't need to write the whole code every time)
2) More accuracy, since it specifically changes the functions.

It might be made into an option in the ClaudeDev, so the user would be able to choose what fits him.

Could the dev make it true? I Believe that would help the app greatly!

**Comment by saoudrizwan** [comment]
This is likely due to Claude trying to edit a large file. I recommend using the Anthropic provider option if you don't already, since it has a max output of 8192 tokens whereas OpenRouter doesn't handle large outputs well and AWS Bedrock is capped at 4096 tokens. You can also try breaking your file down into smaller files.

I also just released v1.1.13 which updates the system prompt to be stricter against lazy coding. Please give it a try and let me know if you still keep running into this issue.
