### ISSUE TITLE
On Deepseek, it gives answer and then starts to loop in inference, over and over.

### ISSUE THREAD

**Issue by m-check1B** [saoudrizwan/claude-dev#87]
Even after reinstall and restarting all, on Deepseek Coder, in VS code, it answers the question and then loops on that question rapidly, again and again. Thank you. (This happens on Ubuntu 24.4.LTS). But same setup works with Claude Sonet 3.5 just fine.

**Comment by JosephShawa** [comment]
Thats happening on AnythingLLM as of the last update. just adding.

**Comment by saoudrizwan** [comment]
This is a problem with deepseek in particular, it's not great at complex tool calling and this endless loop problem has been seen in other projects that also prompt it to go step-by-step. Gonna leave this issue open so others are aware, but I suggest sticking with claude 3.5 sonnet since it's the only model good enough to take advantage of claude dev's massive system prompt and tool schema. gpt-4o is the only thing that comes even close, and all the other models barely scratch the surface. In fact I tried every model capable of tool calling on openrouter and even llama 3.1 and cohere command-r performed so badly I didn't even bother adding them as options.

**Comment by jadams777** [comment]
I'm having the same problem.

**Comment by saoudrizwan** [comment]
Adding DeepSeek as a provider is on the roadmap, closing as duplicate https://github.com/saoudrizwan/claude-dev/issues/119
